version: "3.9"

services:
  shutthebox:
    build: .
    container_name: shutthebox_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app.py